
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255),
                       role VARCHAR(50)
);

CREATE INDEX idx_users_email ON users (email);


CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description VARCHAR(2000),
                          price NUMERIC(19, 2) NOT NULL,
                          quantity INT NOT NULL,
                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP,
                          deleted_at TIMESTAMP
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT,
                        order_total NUMERIC(19, 2),
                        created_at TIMESTAMP
);

CREATE INDEX idx_orders_user_id ON orders (user_id);


CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id BIGINT NOT NULL,
                            product_id BIGINT,
                            quantity INT,
                            unit_price NUMERIC(19, 2),
                            discount_applied NUMERIC(19, 2),
                            total_price NUMERIC(19, 2),
                            CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX idx_order_item_order_id ON order_item(order_id);

-- Demo users (passwords must be BCrypt hashes)
-- Password is abcd1234
INSERT INTO users (name, email, password, role) VALUES
                                                    ('Super Admin', 'admin@example.com', '$2a$10$ALcEMW7SR.5/60DYxGL9dOOEDoZHxzFztZjyuHz30soMes9pVV/D.', 'ADMIN');